### ISSUE TITLE
Lense tube maker

### ISSUE THREAD

**Issue by gamecompiler** [PingvinOpenTag/LTAscetic#10]
Id found it useful to print Lense holder tubes.
Here is a OpenSCAD script.
[optic.zip](https://github.com/PingvinOpenTag/LTAscetic/files/92396/optic.zip)

If you wont install OpenSCAD. Use the thingiverse costumizer.
http://www.thingiverse.com/thing:1271102

**Comment by PingvinOpenTag** [comment]
ОК
