### ISSUE TITLE
Ideas for improvements

### ISSUE THREAD

**Issue by ghost** [PingvinOpenTag/LTAscetic#11]
Hi, i would suggest us to do a COMPLETE rewrite of code and hardware.
I started my self a repo (i will delete in future, it was just a collection of my ideas).
And here is what id found out while playing Lasertag in a Arena, what would be cool in future, while developing sth new:

New Hardware assets and features:
- Ammo, Health and Life boxes, via RFID (Done at hardware side, only need to upload)
- Towers for Towerdefense, also via RFID (Done at hardware side, only need to upload)
- RFID Entry gate to register guns joining the game
- Targets which are RF connected and maybe trigger events 
- DMX Devices (Done at hardware and software, eassily, useable over Serial Bus,)
- No Display required, manageable over PC-side software (Which is almost done, we need to try again to get me writing rights into repo)
- RF via NRF24L01
- Integrated LiPo loader and Fuel Gauge (Done, just need to upload, also with Tricky Infrared led circuit i will figure out later)
  - MCP73831 LiPo Battery Charger
  - MAX17048 LiPo Battery Fuel Gauge
- Tricky Infrared led circuit (see images in the end), to save power and needed parts.
- ws2812b connector ? Maybe funny for kids, to have lasertag like blinking guns
- Schematic in Eagle

Modes:
- Zombie (Id never understood how to play that Oo)
- Juggernaut
- Team
- FFA
- Tower defense
- Capture the Flag (RFID Flag)
- Shot em (Im sure this do not exist, i thaught a game mode where you have to shot targets faster than your "Enemy" would be col
  *... Do you know more ?

To get the pc side running i would like to have a NRF24L01 MASTER node using RF24 MESH library.
Here is a list of commands i would like to have (My pc side applications awaits this commands at this time)

```
--------------------------------------
--                                  --
--                                  --
--          __  COMMANDS __         --
--                                  --
--------------------------------------

---------------------
--  __Playername__ --
---------------------

/get playername device //Get playername which is currently assigned at device
/set playername device //Set a playername at device

---------------------
--  __Devices__ --
---------------------

/get device <device>//Get status of device, like a ping
/list device //List all device connected to master

---------------------
--  __Respawn and Life__ --
---------------------

/set respawntime <amount> [playername]  //Needed for every player to make Juggernaut and Kingofthehill more fair
/get respawntime [playername] //Get respawntime for playername

/set max life   <amount>    [playername]    //Set maximum of lifes, so that some people cant have 99 lifes because they know how to get extra lifes
/set start life <amount> [playername]   //Sets the amount of lifes the player will start



----------------
--  __Score__ --
----------------

Score is handled by PC-side

----------------
--  __Ammo__  --
----------------

/set start ammo <amount> [playername]//Sets the amount of ammo the player will start

/get ammo <playername> //Returns current ammo amount of playername
/set ammo <playername> <amount> //Sets playername ammo at amount

----------------
--  __Health__--
----------------

/set max health <amount>    [playername]    //Set maximum of health  [for playername]
/set start health <amount> [playername] //Sets the amount of health the player or all will start

/get health <playername> //Returns current health amount of playername
/set health <playername> <amount> //Sets playernames health at amount

----------------
--  __Team__ --
----------------

/get team <playername>  //Returns teamname of playername
/set team <playername> <teamname> //Sets playernames team to teamname
/list team  //Returns all teams and playernames assigned to teams

----------------
--  __Sound__ --
----------------

/set soundlevel [playername] [device] //Sets the sound level of device or playername

```

Here in the end are some chematics, first one design i did, still need to make a pdf of the complete lasertag design with Lipo charger and RFID reader. Currently i have uploading problems again....

https://github.com/gamecompiler/SKIRMTAG/blob/master/hardware/SKIRMTAG.pdf

Greetings from germany.
I would like to see LTAscetic to be as good as commercial Lasertag guns.

Ah, before if forget it, id made the Lasertag Lense Tube Configurator id made before ready to be run on a simple php website.

P.S the background is animated in the Highscore screen (Video loop used from dreamscene, called Moonview)
![unbenannt](https://cloud.githubusercontent.com/assets/7261213/12367228/b588eb16-bbe0-11e5-9820-48e248d1029d.png)

**Comment by PingvinOpenTag** [comment]
Many of these you I want to realize the project "Armata".
Already 90% of the work done.
If you want to participate development project Armada - I'll give all the sources.

**Comment by gamecompiler** [comment]
Ok, i swear i would not.
So if i participate in ARMada,
we have to talk over E-Mail.
 
I close this issue.
Would be awesome if my Software would run "almost" Out of the Box with ARMada.

Greetings from Germany, 
gamecompiler.

**Comment by PingvinOpenTag** [comment]
I am using a development environment CooCox. 
http://www.coocox.org

Check your Mail?

**Comment by gamecompiler** [comment]
I did check, at this time i did not receive a E-mail Oo. Im sorry.
But id found some errors in the forum,

[ul]
  [li]TEXT[/li]
  [li]Texst[/li]
[/ul]

Does not work.

**Comment by PingvinOpenTag** [comment]
Did you not login and password, do not enter. I sent them to your е-mail.

**Comment by gamecompiler** [comment]
? No im confused. I do not understand what you mean.

If you mean the login details for the forum e.t.c.
Im already in work, id received them already.

But i did not received the ARMada code if you mean that.



Am 16.01.2016 um 15:50 schrieb Pingvin:

**Comment by PingvinOpenTag** [comment]
I see your message on the forum!
What does not work?

**Comment by gamecompiler** [comment]
If i make a unsorted list.

[ul]
[li]TEXT[/li]
[li]Texst[/li]
[/ul]

The dots that should be visible do not appear.

**Comment by gamecompiler** [comment]
Huge update !
Im sorry that i did not posted any updates a long time,
ive got many problems with my 3D printer, but now he works well.

Ive remixed dan0nator Halo Gun Design for lasertag.
Its now designed to fit 2 Lipo packs @ 2000mAh, a esp8266, the lense, rumble motor, and a piezo speaker (in future a better one).

![test1](https://cloud.githubusercontent.com/assets/7261213/17447643/ef60a14e-5b4f-11e6-97f4-02b2c7d2d1af.jpg)

Also almost ready is a IR sensor holder (Id damaged 7 of them cause of ESD.... So this is a resolution).
![unbenannt](https://cloud.githubusercontent.com/assets/7261213/17447727/6ef6ba60-5b50-11e6-97af-ffa58826da4a.png)

Files will be uploaded when they work 100%, i and a friend will check everything working on 8.8.2016.
Hope your are well ;D

What happend with the LTAscetic Homepage ?
Im able to login, but cant write any articles Oo!

With king regards,
gamecompiler

**Comment by gamecompiler** [comment]
The password reset function does not work on http://armada.ltascet.com.
Anyway, here are again some updates of my ir sensor holder,
id made 3 more versions today. The new versions add cable holes to hide the cables. 
Im not sure if its good to let the cables go out under the top. Maybe it would be better to let them go out on the sides. What do you think ? Where should the cables go out ?

![unbenannt](https://cloud.githubusercontent.com/assets/7261213/17455697/694a2d66-5bc0-11e6-8c87-8384ac1eb6e2.png)

**Comment by gamecompiler** [comment]
![img_20160807_125642](https://cloud.githubusercontent.com/assets/7261213/17462003/83bfcfaa-5c9e-11e6-84d5-0c8df95a07d5.jpg)

**Comment by PingvinOpenTag** [comment]
Cool!

**Comment by PingvinOpenTag** [comment]
Send me an e-mail a new password, I will change
