### ISSUE TITLE
Pleases add a part list

### ISSUE THREAD

**Issue by gamecompiler** [PingvinOpenTag/LTAscetic#4]
Id made a part list for the LTAscetic 3.1 release.

Part list for de.mouser (Use at your own Risk and please check !)
If checked please add it to the Readme.md

LTA Motherboard (3.1)
http://www.mouser.com/ProjectManager/ProjectDetail.aspx?AccessID=8740157a16 

LTA Ir Sensor	(3.1)

http://www.mouser.com/ProjectManager/ProjectDetail.aspx?AccessID=37c73c7856

**Comment by PingvinOpenTag** [comment]
Ascet-configurator port from PC to Android
http://www.youtube.com/watch?v=n5ikXYz3mhE

Upload sounds use configurator on Android 
http://www.youtube.com/watch?v=lW9ozMrs18M&feature=youtu.be

**Comment by gamecompiler** [comment]
Could we use the NJM386 IC ?
Its avaible as DIP.
Or we use the SMD edition of the NJM386 IC. 
You would need to change the pcb if we use the SMD edition.

What should we do ?

**Comment by gamecompiler** [comment]
One Question, about the LCD-universal-Modul.
What data is owned by the Q1-BC847 and U1-MC74HC595AD (I only need the case type).
I will publish some more part lists if im ready.

Could you please send me a fix of the Bluetooth modul pcb DIPTrace_files ? I cant read the DIPTrace_files without problems. Part 1-2, i see something dont readable for me, my pc cant decode the russian language, i think.
![screenshot 3](https://cloud.githubusercontent.com/assets/7261213/5729207/efdd2340-9b70-11e4-8e05-57c08d25c19f.png)

Thanks in Advance

**Comment by PingvinOpenTag** [comment]
And where do NJM386 IC?
It's a completely different chip, as I understand it.
Or it is a complete analog TDA7052A?

Сhange the pcb  can by anything, a matter of expediency.
I have no such need.

**Comment by PingvinOpenTag** [comment]
BC847 has the same body as irlml2502  - SOT-23 (SMD).
74HC595D - SOIC-16 (SMD)

**Comment by gamecompiler** [comment]
Id have problems ordering the Matherboard pcbs, could you export the gerber files as GBR files please ?

Freepcb wont let me do that.
Thanks in Advance.

**Comment by PingvinOpenTag** [comment]
Complexity of translation.
I do not understand - from what program you want to export Gerber files?
And what of the PCB?

**Comment by PingvinOpenTag** [comment]
I'd like to know more about your hardware.
Where to order the production of printed circuit boards?
Which configuration using ascetic?
Few photos, video ...
Could bring some joy to the old man?

**Comment by gamecompiler** [comment]
Id ordered my pcbs at www.dirtypcbs.com.
They are not as dirty as id thought.
I will post pictures if id received them, and id built them.
Yes i could send some joy to the old man :).
But first i need to receive them.

I have following problems currently ordering the pcbs.

I need following types of data

Gerber file extension 	Layer
GTO 	Top Silkscreen (text)
GTS 	Top Soldermask (the 'green' stuff)
GTL 	Top Copper (conducting layer)
GBL 	Bottom Copper
GBS 	Bottom Soldermask
GBO 	Bottom Silkscreen
GML/GKO/GBR* 	Board Outline*
TXT 	Routing and Drill (the holes and slots)

First attempt was to convert the existing files to the needed files.
Id fail....

At this moment i redesign the Board in eagle; They also can use brd files.
The problem is that i will need to have this files in this night.
I think i will have a long night....

**Comment by gamecompiler** [comment]
WARNING: Id found a lot of Erros, in the mouser part-liste.
Mouser did deledt some product pages, im not sure why....
Please DO NOT USE IT....
I need to fix that problems....
So many problems this night.... ARGH

**Comment by gamecompiler** [comment]
Id redesigned the IR_Sensor in Eagle, i think this new design looks better.
And its a little bit cheaper to produce.
http://www.file-upload.net/download-10147101/export_IR_Sensor.zip.html

**Comment by gamecompiler** [comment]
UPDATE: My new redesigned layout:
Do you think its ok ?
Sorry im under stress....

IR_SENSOR

http://dirtypcbs.com/order_images/13d093c9d5b35f3950eb14d471d986d7-4080_bottom.png
http://dirtypcbs.com/order_images/13d093c9d5b35f3950eb14d471d986d7-4080_top.png

LCD_UNI....

http://dirtypcbs.com/order_images/13d093c9d5b35f3950eb14d471d986d7-4081_bottom.png
http://dirtypcbs.com/order_images/13d093c9d5b35f3950eb14d471d986d7-4081_top.png

**Comment by PingvinOpenTag** [comment]
FreePCB perfectly formed Gerber files!
Only for some reason he gives them another extension.
Do not worry, you can rename.
Gerber files are in the repository.
I did not do the Silks only
I did not do the inscriptions only Copper, Soldermask, Board Outline, Drill layers.

**Comment by PingvinOpenTag** [comment]
What you do not like my version of the LCD module?
http://raw.githubusercontent.com/PingvinOpenTag/LTAscetic/master/release_2%28LCD,Joystck,TouchMemory,Reload,Antichiter,IrPowerControl,BattaryControl%29/hardware/pcb/lcd_shield_smd_layout.jpeg

**Comment by PingvinOpenTag** [comment]
Blame !!!
Gerber files LCD module is not in the repository 2 release!
I mast to fix it!


I have Gerber files on all PCB that are laid out in the repository!

**Comment by PingvinOpenTag** [comment]
GERBER for LCD module release 2.
https://yadi.sk/d/NVg_-IIMdykhL

**Comment by PingvinOpenTag** [comment]
Why do you have such thin tracks on the boards?

**Comment by gamecompiler** [comment]
Thanks for your gerber Files.
And a HUGE thanks for the tipp to rename the files.
I will try it out now.
I like your LCD_Shield Design ! But id thought i have to redesign everything in eagle.
Id also started last night to redesign the Matherboard in eagle.
I like more my IR_Sensor Design. I think it will be easier to wire to the head and shoulders.

Why such thin tracks ?; I do not know, id thought it will be enough thick. There is no really reason why id maked it as thin as it is.

**Comment by gamecompiler** [comment]
Worked. Thank you !
Suuuch much thanks !

Cant await when they become shipped ;D

**Comment by PingvinOpenTag** [comment]
So you do not have workers pay an "Аscetic"?
But you wrote that using them together with your friends!
What I do not understand ...

**Comment by gamecompiler** [comment]
Now i do not understand you.
But i think I know what you do not understand.

I let my pcbs produce by www.dirtypcbs.com.
I and my friends already use LTAscetic, but dirty built on Breadboards.
So id decided to produce everything as pcb.
Yes my friends pay money to me, i build the Lasertag weapons for them.

Im not sure what you did not understand. Sorry.
And what do you mean with workers ?
Workes pay an Ascetic ?!? Huh ?

Im a Student in the 11. class.
Just to say it. I do not own a company.

**Comment by PingvinOpenTag** [comment]
It's all  translator!
"рабочая плата" (works PCB) not "заработная плата" (Wages)

I wrote verbatim "Так у Вас нет рабочих плат Аскета? "
And the correct translation would be
"So you do not have workers PCB an ascetic?"
Here's a lesson in linguistics turned out!

**Comment by gamecompiler** [comment]
I think we should create a Scoring Utility for Android.
I think it would be awesome to see Scores on a huge TV Screen using a Android TV Settop-Box.

Could you share your Code of your Android-APP ?
And could you make a Documentary how the Bluetooth/Serial commands work (A list would be enough) ?

Could i add lives or ammo to somebody over Bluetooth ?
Could we add a gamemode type like Capture of the Hill or Capture the Flag ?
First the code should be cleaned up ! What happend with Intensitiveclod ?
Is he/she already ready ? Did he/she already started ?

**Comment by gamecompiler** [comment]
Part list updated

B45196H2476M309 is now knowed as T491C476M010AT.
That was the problem

**Comment by PingvinOpenTag** [comment]
Thanks for the offer, but I order the board in a nearby town - Novosibirsk.
I order as empty board and partially assembled (soldered resistors and capacitors on one side).
Obtained cheaply - at today's exchange rate of one part of the cost of the board has collected about 2 euros.
A fully assembled printed circuit board (he soldered transistors, diodes, socket for the amplifier and controller) - about 5-6 euros at today's exchange rate.
How much you pay?

**Comment by PingvinOpenTag** [comment]
Utility to Androd "Аscetic-сonfigurator LITE" in the repository.
I created it in App Inventor.
The current code that I ported from the PC I'll post.

**Comment by PingvinOpenTag** [comment]
Bluetooth for you while you can adjust the parameters of the game, which will be the player after the start of the game (number of rounds, the number of clips, life, color team, player ID, etc.)
During the game, nothing to configure the tablet while it is impossible, as the channel takes a bandana.

But I have already said that work on more interesting system, and when the tag and bandana will be connected to your tablet or smartphone via Bluetooth.
Already a tablet or smartphone can transmit data and WiFi and cellular communication.
And on the local server and the remote via the Internet.

But this should zanisatsya, I, too, just a man, and not God!
Both my family and work, not just a hobby.
Therefore, open the project, I hope to help.

**Comment by gamecompiler** [comment]
Wow your pcbs in Russia are very cheap, i have to pay c.a 30 Euros for Display,PCBs(LCD + Matherboard) and Electtronics for the pcbs.
15 Euro Electronics for the Matherboard
4.56 Euro Electronics for the IR Sensor
c.a 5 Euro Electronics for the LCD_Shield
c.a 10 Euro for the Display.
7 Euro for the pcbs.

Now i really think german is too expansive.
Made in Germany, made my day....

**Comment by PingvinOpenTag** [comment]
As for the teams - open the file

https://github.com/PingvinOpenTag/LTAscetic/blob/master/release_3_1(SMD%2Cfix_flesh_led_bag%2Cfirmware_up_to_56000Hz_IR_F0)/firmware/LTAscet_3_1_Atmega32/source/LTAscet_blue_stop_isr_up_to_56000HZ_IR_F0/commands.h

 then describes all the commands that are understood Ascet.

Of course it is necessary to write a description, but once all the time lacking.

**Comment by PingvinOpenTag** [comment]
So after the ruble has fallen off sanctions!
Therefore, if you convert to the euro, we all really cheap!
And the first order is always more expensive because of the pre-production.
Want, I will inquire the account on a partially assembled motherboard?
Can and sensors, but I ordered a kit, with collating chit will be more expensive, but Mogi and learn about them.

**Comment by gamecompiler** [comment]
Sorry, but i dont understand you

-->
Want, I will inquire the account on a partially assembled motherboard?
Can and sensors, but I ordered a kit, with collating chit will be more expensive, but Mogi and learn about them.
<--

**Comment by PingvinOpenTag** [comment]
I can ask to me to issue an invoice for the production of printed circuit boards.
For comparison.

**Comment by gamecompiler** [comment]
Ah ok. Thx, i think id understood you.
Can you give me access to your joomla site ?
I would start to write Documentary; how to use LTAscetic e.t.c.

**Comment by PingvinOpenTag** [comment]
OK!
True, I still end up with a template is not defined.

Went to create a user.
Send your password by email.

**Comment by PingvinOpenTag** [comment]
I sent a letter to check the mail.

**Comment by gamecompiler** [comment]
Thanks.Could you please put the Joomla GUI into english ?I cant read everything Oo-------- Originalnachricht --------Betreff: Re: [LTAscetic] Pleases add a part list (#4)Von: Pingvin An: PingvinOpenTag/LTAscetic Cc: Jason I sent a letter to check the mail.

**Comment by gamecompiler** [comment]
Soory works. Id changed my local browser language to russian to be able to read russian.
Works now

**Comment by gamecompiler** [comment]
Id found sth wrong, LTAscetic Matherboard 3_1 pcb files.

C1-C2 has package C1206thermal but a C0603thermal footprint.

R2-R4 has package C1206thermal but a C0603thermal footprint.
R6-9 has package C1206thermal but a C0603thermal.
R10 - R12 has package C1206thermal but a C0603thermal footprint.
R21 has package C1206thermal but a C0603thermal.
R37 has package C1206thermal but a C0603thermal.

X1 has no package on pcb files, what package is needed ?

Z1-4 has no package on pcb files, what package is needed ?


C11 has no package on pcb files, what package is needed ?
C15 is this part correct ?
http://www.mouser.de/Search/ProductDetail.aspx?R=EEE-FK1A102Pvirtualkey66720000virtualkey667-EEE-FK1A102P
C16 has no package on pcb files, what package is needed ?
C28 has no package on pcb files, what package is needed ?
C33 has no package on pcb files, what package is needed ?

Thanks in Advance.

**Comment by gamecompiler** [comment]
What do yo mean with that ?
Terminal for connecting the reader dongle TouchMemory («pill"), or other devices that use 1-wire interface.

For what do i need this TouchMemory ?

**Comment by gamecompiler** [comment]
Sorry, id found ever info for the packages on your homepage.
The DIPTrace files should be changed to the correct packages !!!
This is very baffling !
And you have some russian language in your English article.

->U3 1 24LC512,512 Кбит (64К x 8) SEEPROM, I2C 400 КГц, 2.5- 5.5 V, SOIC-8

**Comment by PingvinOpenTag** [comment]
What do yo mean with that ?
Terminal for connecting the reader dongle TouchMemory («pill"), or other devices that use 1-wire interface.

For what do i need this TouchMemory ?
---------------------------------------------------------------------------
That players could not start the game itself, but only the referee can start the game. Only the referee can change the settings tag.
But with the advent of remote and settings for Bluetooth is no longer relevant.

**Comment by PingvinOpenTag** [comment]
The DIPTrace files should be changed to the correct packages !!!
This is very baffling !
-------------------------------------------
LTAscetic Matherboard 3_1 pcb is not done in DipTaсe, can you mean FreePCB?

**Comment by gamecompiler** [comment]
Sorry, yes i mean freepcb.-------- Originalnachricht --------Betreff: Re: [LTAscetic] Pleases add a part list (#4)Von: Pingvin An: PingvinOpenTag/LTAscetic Cc: Jason The DIPTrace files should be changed to the correct packages !!!

This is very baffling !

LTAscetic Matherboard 3_1 pcb is not done in DipTaсe, can you mean FreePCB?

**Comment by gamecompiler** [comment]
How do i start a game ?-------- Originalnachricht --------Betreff: Re: [LTAscetic] Pleases add a part list (#4)Von: Pingvin An: PingvinOpenTag/LTAscetic Cc: Jason The DIPTrace files should be changed to the correct packages !!!

This is very baffling !

LTAscetic Matherboard 3_1 pcb is not done in DipTaсe, can you mean FreePCB?

**Comment by PingvinOpenTag** [comment]
How do i start a game ?
-------------------------------------------

If the key Touch Memory is not stored in memory, simply press "reload".
If recorded - Touch Memory key attaching to the reader.
