### ISSUE TITLE
[SOLVED]    Which compiler has been used ?

### ISSUE THREAD

**Issue by gamecompiler** [PingvinOpenTag/LTAscetic#5]
Hi, id started the translation progress, and id merged 
insensitiveclod´s code with my code.

Now i would like to compile the code.
Which version of AVR Studio and compiler should i use ?
Id saw version 4 has been used. Which version of Studio 4 ?
Did you use WinAVR ? Or other kind of Software ?

Thanks in Advance.

**Comment by PingvinOpenTag** [comment]
Yes, WinAVR  compiler I use.
AVR Studio 4.16-4.18.
Not 4.19!!!!

**Comment by gamecompiler** [comment]
Please add this to the Readme
