### ISSUE TITLE
Lasertag introduction for Readme

### ISSUE THREAD

**Issue by gamecompiler** [PingvinOpenTag/LTAscetic#6]
Hi, id translated the following text.
http://www.contronik.net/cgi-bin/contronik.pl?site=laser_tag
I think its a good text.

I think its the perfect text for our Readme.
Please check for spelling mistake

-------Text Start----------

Lasertag, also known as Laser Game or Laserspiel, is a strategy and sports game that demands
on accuracy, responsiveness and endurance. Its similiar to paintball.
But you dont shot with paintballs. Your Enemy will be marked by a little infrared signal which will be
evaluated by a electric receiver.
This makes Lasertag absolute harmless as a contrast to paintball.
No one runs to get in danger, you wont become dirty and you wont become hit by high-speed flying color balls.
First and foremost Lasertag is about the fun, tactics and teamwork skills to the fore.
And its better to participate into a Lasertag game instead of pressing just the mouse button on the computer.

To play Lasertag, you need a Gamergear, named Tagger.
Taggers are not cheap, a Tagger cost an average of 500 to 750 Euro.
Therefore we offer you a complete Open-Source Lasertag Tagger design, LTAscetic.
All schematics, PCB layouts and software codes are completely free to use for 
non-commercial purposes.

For playing at least two persons or more are required, each person has to wear a Tagger and a associated receiver.
The receivers are attached to the body of the player.
Either they are attached to the upper body, back and shoulder.
Anpther method is to carry the receiver as a headband on the head.
Therefore we have a Bluetooth receiver headband and a wired one, see Sourcecode.
In genereal, three receivers are placed on the body.
All recipients are electrically connected to each other with a cable or via Bluetooth to the Tagger.
The evaluation of a hit takes place on the electronics of the taggers.
LTAscetic also offers a Anticheat feature at this time in the 3.1 Experimental Release.

We cordially invite you to use our Project for non-commercial purposes.
Have fun !

Text is in other form originally located in German at http://www.contronik.net/cgi-bin/contronik.pl?site=laser_tag.

Text end----------------

One question, how can we mark Issues as solved ?!?

**Comment by PingvinOpenTag** [comment]
All schematics, PCB layouts and software codes are completely free to use for
non-commercial purposes.
---------------------------------------------
How Come?
Let it be completely free license.
Including for commercial use.
What do you think?

**Comment by gamecompiler** [comment]
I agree with you , it's probably better if the project is completely free to use , distributors are allowed to produce the project.

Id changed the text for Commercial license now.

-------Text Start----------

Lasertag, also known as Laser Game or Laserspiel, is a strategy and sports game that demands
on accuracy, responsiveness and endurance. Its similiar to paintball.
But you dont shot with paintballs. Your Enemy will be marked by a little infrared signal which will be
evaluated by a electric receiver.
This makes Lasertag absolute harmless as a contrast to paintball.
No one runs to get in danger, you wont become dirty and you wont become hit by high-speed flying color balls.
First and foremost Lasertag is about the fun, tactics and teamwork skills to the fore.
And its better to participate into a Lasertag game instead of pressing just the mouse button on the computer.

To play Lasertag, you need a Gamergear, named Tagger.
Taggers are not cheap, a Tagger cost an average of 500 to 750 Euro.
Therefore we offer you a complete Open-Source Lasertag Tagger design, LTAscetic.
All schematics, PCB layouts and software codes are completely free to use for
non- and commercial purposes.

For playing at least two persons or more are required, each person has to wear a Tagger and a associated receiver.
The receivers are attached to the body of the player.
Either they are attached to the upper body, back and shoulder.
Anpther method is to carry the receiver as a headband on the head.
Therefore we have a Bluetooth receiver headband and a wired one, see Sourcecode.
In genereal, three receivers are placed on the body.
All recipients are electrically connected to each other with a cable or via Bluetooth to the Tagger.
The evaluation of a hit takes place on the electronics of the taggers.
LTAscetic also offers a Anticheat feature at this time in the 3.1 Experimental Release.

We cordially invite you to use our Project for non- and commercial purposes.
Have fun !

Text is in other form originally located in German at http://www.contronik.net/cgi-bin/contronik.pl?site=laser_tag.

Text end----------------

**Comment by PingvinOpenTag** [comment]
OK!

**Comment by PingvinOpenTag** [comment]
Abusing his official position, I created a website on the corporate server of the company where I work.
armamd.ltascet.com
Multilingual website, is there and the German language. So you can prepare articles for publication on the website. And if you are familiar with joomla, I can give you administrator access.

**Comment by gamecompiler** [comment]
Yes i now joomla a little bit.
I really would like to write articles for publication on your website.
But do you not thing that adminstrator access is a little bit to heavy ?
I will not abuse the rights, but joomla offers also a moderator user.
A moderator user can write and create pages.
I think that would be enough.

Thanks in Advance.

**Comment by PingvinOpenTag** [comment]
I am ready to give you any rights you desire! ;-)

**Comment by PingvinOpenTag** [comment]
Text is in other form originally located in German at http://www.contronik.net/cgi-bin/contronik.pl?site=laser_tag.
---------------------------------------------------
Excellent site!
And I do not know anything!
This is your project?

**Comment by gamecompiler** [comment]
No it is not my Site.
Id first built this device on contronik.net.
It looks very cool, but the shoot range is kind of boring.
And there are no game types and so on.
After that id researched a little bit more and id found your Project.
Just to say it, your Project is very hard to find.
On my research id found LTAscetic on google search page 20 or so.

**Comment by PingvinOpenTag** [comment]
It's all fucking translator!

In Russian, the word "плата" has two meanings - "печатная плата" (PCB) and  "плата за работу" (payment for work)!
I wrote verbatim " Так у Вас нет рабочих плат Аскета?"
And the correct translation would be
"So you do not have workers PCB an ascetic?"

"рабочая плата" (works PCB) and "заработная плата" (Wages)   Immersed completely different meaning!

Here's a lesson in linguistics Recipients! ;-)

Once again - the project is absolutely free!
If anyone can make money on it - very good!

**Comment by gamecompiler** [comment]
Ah ok :)
Id thought you may be interessted what files id send dirtypcbs now. 
I now produce your ir_sensor, because for no reason they wont read my brd files correct....

Here are the files.
http://www.file-upload.net/download-10149853/toproduce.zip.html

**Comment by gamecompiler** [comment]
And here my dirtypcb Eagle 6 konfiguration, maybe somebody need it later.
http://www.file-upload.net/download-10149860/dirtypcb.dru.html
