### ISSUE TITLE
Create a makefile ?

### ISSUE THREAD

**Issue by gamecompiler** [PingvinOpenTag/LTAscetic#7]
Hi, 
I think a makefile would be great.
If im correct, the firmware is compiled by winAVR.
It would be easier to let a makefile do everything.
Then also Linux users could compile the firmware.
I think its easier to download winAVR than installing a specifed AVR Studio Version.
Under and above Windows 8 the older versions of AVR Studio are a huge problem.
If somebody read this and know who to use winAVR, i please to this person to create a makefile.

Thanks in Advance.

**Comment by PingvinOpenTag** [comment]
Projects easily imported into 6 studio.
Well, I 'll look for that file

Воскресенье, 22 февраля 2015, 11:57 -08:00 от Jason <notifications@github.com>:

**Comment by gamecompiler** [comment]
Done, worked.
