### ISSUE TITLE
Part list, updated

### ISSUE THREAD

**Issue by gamecompiler** [PingvinOpenTag/LTAscetic#8]
Hi, im back.
Id updated the part list, i please you to check it.

http://www.mouser.com/ProjectManager/ProjectDetail.aspx?AccessID=4928c44ff5

Id added as replacement for the TDA7052, the SO-8 of the TDA7052 version.
Id got a new email address. So please don´t wonder if you get e-mails from xxxx@strongforce.de. (I have a website now Oo!)

I have a good source of optics now.
Google card box lenses with 

Diameter: 25mm
Focal Length: 45mm

are perfectly for TSUS5202 Infrared Emitting Diodes (15 degree).

Thanks in advance.
Greetings from germany :smile:

**Comment by PingvinOpenTag** [comment]
TDA7052AT/N2,118   - it's SO-8 case?
I use DIP case.

**Comment by gamecompiler** [comment]
That should be no Problem because the footprint fits. Its just in Z-Axis smaller.
